'use strict';

const { TYPE_SECTIONS } = require('./core');

function bullet(c) {
  const scope = c.scope ? `**${c.scope}:** ` : '';
  return `- ${scope}${c.text} (\`${c.hash}\`)`;
}

/**
 * Render one changelog section (markdown) from parsed commits.
 * @param {{ commits: Array, version: string, date?: string }} input
 * @returns {string}
 */
function renderSection({ commits, version, date }) {
  const when = date || new Date().toISOString().slice(0, 10);
  const lines = [`## ${version} — ${when}`, ''];
  const breaking = commits.filter((c) => c.breaking);
  if (breaking.length > 0) {
    lines.push('### ⚠ BREAKING CHANGES', '');
    for (const c of breaking) lines.push(bullet(c));
    lines.push('');
  }
  for (const [type, heading] of TYPE_SECTIONS) {
    const group = commits.filter((c) => c.type === type);
    if (group.length === 0) continue;
    lines.push(`### ${heading}`, '');
    for (const c of group) lines.push(bullet(c));
    lines.push('');
  }
  const others = commits.filter((c) => c.type === 'other');
  if (others.length > 0 && commits.every((c) => !['feat', 'fix', 'perf', 'refactor', 'docs', 'test', 'build', 'ci'].includes(c.type))) {
    lines.push('### 🔧 Other', '');
    for (const c of others) lines.push(bullet(c));
    lines.push('');
  }
  return lines.join('\n').trimEnd() + '\n';
}

/**
 * Render the CHANGELOG.md header used by --init.
 */
function renderInit() {
  return '# Changelog\n\nAll notable changes to this project are documented in this file.\n\nGenerated by [changelog-genie](https://github.com/Dukk11/changelog-genie) 🧞 — keep your commits conventional and this file writes itself.\n\n';
}

module.exports = { renderSection, renderInit };
